### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by SeBin-Kwon** [SeBin-Kwon/NC1-TodoBiny#1]
# Todo

- [ ] 리스트 사용하면서 슬라이더 구현(선택 삭제 되야함)

- [ ] 탭뷰 스와이프
- [ ] 할일 수정 구현
- [ ] 할일 글자 수 제한
- [ ] 키보드 다른 곳 눌렀을 때 내려가게 하기
- [ ] 디테일뷰 날짜별 진행률 기록
- [ ] 할일 색상 랜덤이면서 안겹치게

- [ ] 코어데이터
- [ ] 검색 기능

- [ ] 설정 - 라이트/다크모드
- [ ] 설정 - 모든 데이터 삭제
- [ ] 위젯, 워치, 잠금화면

- [ ] 로고 및 네이밍, 로고모션
- [ ] 완료시 이펙트(햅틱, 사운드, 애니메이션)
- [ ] 할일 롱제스처로 색상 변경
